// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCQyzfqbXe_qZebzJaFiYWPuI95p_mjE',
    appId: '1:1007275888838:web:587c6837530fa3942b07c7',
    messagingSenderId: '1007275888838',
    projectId: 'firestoredemo-28c7c',
    authDomain: 'firestoredemo-28c7c.firebaseapp.com',
    storageBucket: 'firestoredemo-28c7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkse4FI6vtPyp5reh7XbYp1gmrjFiJmI',
    appId: '1:1007275888838:android:58aea994b68d209e2b07c7',
    messagingSenderId: '1007275888838',
    projectId: 'firestoredemo-28c7c',
    storageBucket: 'firestoredemo-28c7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg0gryanPWH4TFkwNnRCEMCBgurSYV-Ms',
    appId: '1:1007275888838:ios:69406659c7f5f4952b07c7',
    messagingSenderId: '1007275888838',
    projectId: 'firestoredemo-28c7c',
    storageBucket: 'firestoredemo-28c7c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPCQyzfqbXe_qZebzJaFiYWPuI95p_mjE',
    appId: '1:1007275888838:web:1ee75008bff16c9d2b07c7',
    messagingSenderId: '1007275888838',
    projectId: 'firestoredemo-28c7c',
    authDomain: 'firestoredemo-28c7c.firebaseapp.com',
    storageBucket: 'firestoredemo-28c7c.firebasestorage.app',
  );
}
